### ISSUE TITLE
MaRdI.sortimages move files option creating duplicates 

### ISSUE THREAD

**Issue by evaalonsoortiz** [shimming-toolbox/shimming-toolbox-matlab#58]
Using MaRdI.sortimages move files option with a mounted drive on Syngo:

Step 1: I moved dicom files from the mounted drive to a working folder (using MaRdI.sortimages with option "0"). 
Step 2: Acquired additional scans and moved those again using MaRdI.sortimages. This resulted in duplicates for the files moved in Step 1. 

![image](https://user-images.githubusercontent.com/6652194/77583560-ab494e00-6eb7-11ea-8c35-42fe61fbcb56.png)

**Comment by rtopfer** [comment]
i can't reproduce the error. 
@evaalonsoortiz does this happen irrespective of the folder?
my guess is that if folder permissions are set to _read only_ it may be that your version of MATLAB just defaults to copying the files because it isn't allowed to move them.

**Comment by evaalonsoortiz** [comment]
@rtopfer I just tried again from another folder (set to read and write) and realized that when I used the option to move files, they are simply copied and not moved. This is definitely not the case for everyone else? @po09i

**Comment by po09i** [comment]
@evaalonsoortiz  Moving the files definitely moves them. Also when I copy them twice, no duplication occurs.

**Comment by rtopfer** [comment]
@evaalonsoortiz have you tried with an input of `false` instead of the `0` (i.e. lowercase, no quotation marks)? (sounds desperate but sometimes Matlab typecasting yields surprises.)
`MaRdI.sortimages` really isn't doing anything much besides reading the dicom headers to choose the filenames before calling Matlab's [`movefile` ](https://www.mathworks.com/help/matlab/ref/movefile.html) or [copyfile](https://www.mathworks.com/help/matlab/ref/copyfile.html) -- see if just using `movefile` on any single file works to move rather than copy it. (also, check out the matlab documentation -- the function supposedly returns status messages, might be a clue there)

**Comment by evaalonsoortiz** [comment]
I found the error, but I am not sure why no one else had this issue. 
When we call `realtime_zshim('phantom', 0)`, the call to MaRdI.sortimages has no "isCopying" boolean
https://github.com/neuropoly/realtime_shimming/blob/397f20dd0bea2f1c3a8ab0226e9c547b5661ec92/example/realtime_zshim.m#L71-L74
If the number of arguments is <3, the default is to copy the files:
https://github.com/neuropoly/realtime_shimming/blob/397f20dd0bea2f1c3a8ab0226e9c547b5661ec92/misc/MaRdI.m#L2801-L2803

So,     https://github.com/neuropoly/realtime_shimming/blob/397f20dd0bea2f1c3a8ab0226e9c547b5661ec92/example/realtime_zshim.m#L73

Needs to be changed to
  `MaRdI.sortimages( unsortedDicomDir, sortedDicomDir, 0 );`
